var a = 'hello';
console.log(a);
var o = 'owu';
console.log(o);
var c = 'com';
console.log(c);
var d = 'ua';
console.log(d);
var e = 1;
console.log(e);
var f = 10;
console.log(f);
var g = -999;
console.log(g);
var h = 123;
console.log(h);
var i = 3.14;
console.log(i);
var j = 2.7;
console.log(j);
var k = 16;
console.log(k);
var l = true;
console.log(l);
var m = false;
console.log(m);
